#!/usr/bin/env python3
"""Generate the AI x Manufacturing interactive landscape HTML file."""

USE_CASES = [
    # PLAN
    {"id":"plan-predictive-01","stage":"plan","tech":"predictive","robotics":False,"name":"Demand Forecasting Engine","oneLiner":"Multi-echelon demand signals fused for S&OP accuracy","how":"Gradient-boosted and temporal fusion models ingest POS, distributor, weather, and macro signals. Hierarchical reconciliation ensures plant-level forecasts roll up consistently to family and SKU.","drivers":["revenue","cost"],"autonomy":2,"maturity":"proven","impact":5,"feasibility":4,"prerequisites":["Clean historical shipment data 24+ months","Master data harmonised across ERP instances","Forecast accuracy baseline established"],"valueRange":"2-5% revenue uplift from fill-rate improvement; 5-15% inventory reduction","keyRisk":"Overfitting to pre-disruption demand patterns; model drift after portfolio changes","exemplar":"Global CPG manufacturer with 12 plants and 800 SKUs"},
    {"id":"plan-predictive-02","stage":"plan","tech":"predictive","robotics":False,"name":"Capacity & Constraint Optimiser","oneLiner":"Finite-capacity planning with bottleneck sensitivity","how":"Mixed-integer optimisation models plant routings, changeover matrices, and labour calendars. Monte Carlo simulation quantifies schedule risk under demand uncertainty.","drivers":["cost","capital"],"autonomy":2,"maturity":"scaling","impact":4,"feasibility":3,"prerequisites":["Accurate routings and standard times in MES/ERP","Changeover matrix maintained","Solver licence and OR expertise on staff"],"valueRange":"3-8% throughput gain on constrained lines; 10-20% reduction in expediting","keyRisk":"Optimisation outputs ignored by planners who distrust black-box schedules","exemplar":"Automotive tier-1 with shared bottleneck paint shop"},
    {"id":"plan-generative-01","stage":"plan","tech":"generative","robotics":False,"name":"S&OP Narrative Copilot","oneLiner":"Drafts executive S&OP pack from live plan data","how":"LLM retrieves current forecast, inventory, and capacity snapshots via structured queries, then generates variance narratives and recommended actions in executive tone. Human reviews before distribution.","drivers":["cost"],"autonomy":2,"maturity":"proving","impact":3,"feasibility":4,"prerequisites":["S&OP data accessible via API or structured export","Prompt templates aligned to executive format","Governance on hallucination checks"],"valueRange":"30-50% reduction in S&OP preparation hours per cycle","keyRisk":"Confident but incorrect variance explanations erode trust in one bad cycle","exemplar":"Industrial equipment maker with monthly global S&OP"},
    {"id":"plan-generative-02","stage":"plan","tech":"generative","robotics":False,"name":"Scenario Planning Assistant","oneLiner":"Natural-language what-if across supply network","how":"Agent orchestrates calls to planning APIs and simulation endpoints based on conversational queries ('What if port X closes for 3 weeks?'). Summarises trade-offs across cost, service, and inventory.","drivers":["risk","cost"],"autonomy":3,"maturity":"emerging","impact":4,"feasibility":2,"prerequisites":["Digital twin or planning sandbox environment","API layer over planning tools","Defined escalation when agent exceeds authority"],"valueRange":"Faster crisis response; hard to monetise — primarily risk mitigation","keyRisk":"Agent acts on stale data during fast-moving disruptions","exemplar":"Pharma network planning team during API supply shocks"},
    {"id":"plan-physics-01","stage":"plan","tech":"physics","robotics":False,"name":"Network Digital Twin for CapEx","oneLiner":"3-D layout + throughput simulation for greenfield/brownfield","how":"Physics-based discrete-event simulation embedded in facility digital twin evaluates layout alternatives, AGV flows, and buffer sizing. Surrogate models accelerate thousands of layout iterations.","drivers":["capital","cost"],"autonomy":2,"maturity":"proving","impact":5,"feasibility":2,"prerequisites":["As-built CAD and material flow data","Simulation expertise to validate models","CapEx decision process willing to use simulation evidence"],"valueRange":"5-15% CapEx avoidance on greenfield; 10-25% logistics cost reduction on re-layout","keyRisk":"Simulation calibrated on current state fails to capture future product mix","exemplar":"Electronics assembler evaluating Southeast Asia greenfield"},
    # DESIGN
    {"id":"design-predictive-01","stage":"design","tech":"predictive","robotics":False,"name":"Design-for-Manufacturability Scorer","oneLiner":"Predicts yield and cost impact of design choices","how":"Regression and classification models trained on historical NPI data score draft BOMs and tolerances for predicted first-pass yield, tooling cost, and cycle time before release to production.","drivers":["cost","capital"],"autonomy":2,"maturity":"scaling","impact":4,"feasibility":3,"prerequisites":["Historical NPI outcomes linked to design attributes","PLM integration for automated scoring","Engineering workflow gate that respects scores"],"valueRange":"5-12% reduction in NPI cost overruns; 15-30% fewer late design changes","keyRisk":"Model trained on legacy processes penalises genuinely novel designs","exemplar":"Medical device OEM with high mix/low volume NPI"},
    {"id":"design-generative-01","stage":"design","tech":"generative","robotics":False,"name":"Engineering Spec Copilot","oneLiner":"Drafts and cross-references technical specifications","how":"RAG over standards libraries, past product specs, and regulatory requirements generates draft specifications with traceable citations. Flags conflicts between sub-system requirements.","drivers":["cost","risk"],"autonomy":2,"maturity":"scaling","impact":3,"feasibility":4,"prerequisites":["Curated standards and spec corpus","PLM document management integration","Engineer review workflow mandatory"],"valueRange":"20-40% reduction in spec authoring time; fewer compliance gaps","keyRisk":"Missing a critical regulatory clause that was not in the retrieval corpus","exemplar":"Aerospace sub-system supplier under AS9100"},
    {"id":"design-generative-02","stage":"design","tech":"generative","robotics":False,"name":"CAD Script & Macro Generator","oneLiner":"Generates parametric CAD automation from natural language","how":"LLM translates engineer intent into CAD API scripts (SolidWorks, NX, CATIA) for repetitive feature creation, drawing updates, and BOM extraction. Runs in sandboxed execution environment.","drivers":["cost"],"autonomy":3,"maturity":"proving","impact":3,"feasibility":3,"prerequisites":["CAD API access and sandboxed execution","Validated script templates per CAD platform","Version control for generated macros"],"valueRange":"15-30% engineering hours saved on repetitive design tasks","keyRisk":"Generated geometry that passes visual check but violates tolerance stack-up","exemplar":"Industrial machinery designer with parametric product families"},
    {"id":"design-vision-01","stage":"design","tech":"vision","robotics":False,"name":"Drawing & Markup Comparison","oneLiner":"Pixel-level diff of engineering drawing revisions","how":"Computer vision compares rasterised drawing sets across revisions, highlighting moved dimensions, changed tolerances, and added notes. OCR extracts and diffs callout text.","drivers":["risk","cost"],"autonomy":2,"maturity":"proven","impact":3,"feasibility":4,"prerequisites":["Standardised drawing export format (PDF/TIFF)","Revision control in PLM","Trained users on false-positive review"],"valueRange":"50-70% faster drawing review cycles; fewer shop-floor surprises","keyRisk":"Missed changes in non-standard annotation formats or handwritten markups","exemplar":"Heavy equipment manufacturer with complex welded assemblies"},
    {"id":"design-physics-01","stage":"design","tech":"physics","robotics":False,"name":"Generative Design Optimiser","oneLiner":"Topology optimisation under multi-physics constraints","how":"Physics-informed neural networks and traditional FEA surrogates explore design space for minimum weight/stiffness targets. Outputs manufacturable geometry with AM or casting constraints.","drivers":["cost","sustainability"],"autonomy":2,"maturity":"scaling","impact":4,"feasibility":2,"prerequisites":["FEA/CFD baseline models validated","Manufacturing process constraints encoded","Post-processing for machinability review"],"valueRange":"10-30% material reduction on structural parts; longer lead time on first articles","keyRisk":"Optimised designs that cannot be inspected or assembled with existing tooling","exemplar":"Automotive lightweighting programme for EV chassis components"},
    {"id":"design-physics-02","stage":"design","tech":"physics","robotics":False,"name":"Assembly Sequence Simulator","oneLiner":"3-D digital mock-up validates assembly order and ergonomics","how":"Physics engine simulates part insertion paths, fastener access, and operator reach envelopes. Flags collisions and impossible sequences before tooling commitment.","drivers":["capital","cost"],"autonomy":2,"maturity":"proven","impact":4,"feasibility":3,"prerequisites":["Complete 3-D CAD assembly model","Ergonomics standards defined","Cross-functional sign-off process"],"valueRange":"Avoidance of one tooling rework typically saves $200K-$2M depending on industry","keyRisk":"Simulation assumes ideal part geometry; real tolerances create fit issues","exemplar":"White-goods manufacturer launching new platform"},
    # SOURCE
    {"id":"source-predictive-01","stage":"source","tech":"predictive","robotics":False,"name":"Supplier Risk Scoring","oneLiner":"Multi-factor supplier failure and delay prediction","how":"Models ingest financial health, geopolitical exposure, quality history, and logistics performance to produce dynamic risk scores. Alerts trigger before PO placement.","drivers":["risk","cost"],"autonomy":2,"maturity":"scaling","impact":4,"feasibility":4,"prerequisites":["Supplier master data with tier mapping","External data feeds (credit, geo, logistics)","Procurement workflow that consumes scores"],"valueRange":"Single avoided line-down event often exceeds $1M; ongoing 2-5% spend risk reduction","keyRisk":"False negatives on novel disruption types not in training data","exemplar":"Multi-national industrial conglomerate with 3,000+ active suppliers"},
    {"id":"source-predictive-02","stage":"source","tech":"predictive","robotics":False,"name":"Should-Cost Modeller","oneLiner":"Predicts fair cost from material, labour, and process drivers","how":"Regression models decompose should-cost from commodity indices, wage rates, process parameters, and complexity factors. Flags outliers in supplier quotes for negotiation.","drivers":["cost"],"autonomy":2,"maturity":"proven","impact":4,"feasibility":3,"prerequisites":["Commodity and labour index subscriptions","BOM-level cost decomposition capability","Category managers trained on model limitations"],"valueRange":"3-8% procurement savings on negotiated categories","keyRisk":"Model misses supplier-specific innovations that justify premium pricing","exemplar":"Automotive OEM sourcing stamped metal assemblies"},
    {"id":"source-generative-01","stage":"source","tech":"generative","robotics":False,"name":"RFP & Contract Drafting Assistant","oneLiner":"Generates sourcing documents from templates and history","how":"LLM assembles RFP sections, terms, and SLA language from approved clause library and prior award history. Highlights non-standard terms for legal review.","drivers":["cost"],"autonomy":1,"maturity":"scaling","impact":2,"feasibility":4,"prerequisites":["Approved legal clause library","Template governance process","Mandatory legal review gate"],"valueRange":"40-60% faster RFP cycle time on standard categories","keyRisk":"Non-standard liability clauses slip through if library is stale","exemplar":"Process manufacturer sourcing raw materials globally"},
    {"id":"source-vision-01","stage":"source","tech":"vision","robotics":False,"name":"Incoming Certificate Verification","oneLiner":"Vision checks material certs against PO specifications","how":"OCR and document layout models extract mill cert fields (grade, heat lot, chemistry). Vision validates stamp authenticity and cross-checks against PO line requirements.","drivers":["risk","quality"],"autonomy":2,"maturity":"proving","impact":3,"feasibility":3,"prerequisites":["Digital cert ingestion pipeline","PO-spec matching rules engine","Human escalation for borderline cases"],"valueRange":"Reduced incoming material holds; 30-50% faster cert processing","keyRisk":"Sophisticated forged documentation bypasses visual checks","exemplar":"Steel fabricator receiving mill certificates from multiple mills"},
    # MAKE
    {"id":"make-predictive-01","stage":"make","tech":"predictive","robotics":False,"name":"Predictive Maintenance on Critical Assets","oneLiner":"Remaining useful life from vibration, thermal, and process signals","how":"Time-series models on sensor streams detect degradation signatures weeks before failure. Work orders auto-generated with parts staging recommendations.","drivers":["cost","risk"],"autonomy":3,"maturity":"proven","impact":5,"feasibility":4,"prerequisites":["Sensor infrastructure on critical assets","Historian with labelled failure events","Maintenance workflow integrated with CMMS"],"valueRange":"10-25% maintenance cost reduction; 30-50% reduction in unplanned downtime on covered assets","keyRisk":"Alert fatigue from false positives erodes operator trust","exemplar":"Chemical plant with 200 rotating assets under monitoring"},
    {"id":"make-predictive-02","stage":"make","tech":"predictive","robotics":False,"name":"Process Parameter Optimisation","oneLiner":"Real-time setpoint adjustment within safe operating envelope","how":"Reinforcement learning or Bayesian optimisation tunes temperature, pressure, and feed rates within validated bounds. Closed-loop recommendations to operators or DCS.","drivers":["cost","sustainability"],"autonomy":3,"maturity":"scaling","impact":5,"feasibility":3,"prerequisites":["Validated process model or sufficient DOE history","DCS integration with override safeguards","Operator training on advisory vs autonomous modes"],"valueRange":"2-8% yield improvement; 3-10% energy reduction on optimised units","keyRisk":"Optimiser explores unsafe region if guardrails are incomplete","exemplar":"Specialty chemicals reactor with batch-to-batch variability"},
    {"id":"make-generative-01","stage":"make","tech":"generative","robotics":False,"name":"Work Instruction Copilot","oneLiner":"Generates and updates shop-floor work instructions from engineering changes","how":"LLM pulls latest BOM, routing, and quality requirements to draft step-by-step instructions with embedded images. Auto-updates when ECO released.","drivers":["cost","risk"],"autonomy":2,"maturity":"scaling","impact":3,"feasibility":4,"prerequisites":["PLM-MES integration for ECO triggers","Standard work template library","Supervisor approval before floor release"],"valueRange":"50-70% faster work instruction updates; fewer defects from stale instructions","keyRisk":"Instruction omits critical safety step not captured in source data","exemplar":"Aerospace MRO facility with frequent engineering changes"},
    {"id":"make-vision-01","stage":"make","tech":"vision","robotics":False,"name":"In-line Surface Inspection","oneLiner":"2-D vision detects cosmetic and coating defects at line speed","how":"Convolutional networks trained on defect libraries classify scratches, dents, and coating anomalies on moving product. Rejects routed automatically with image evidence.","drivers":["cost","quality"],"autonomy":3,"maturity":"proven","impact":4,"feasibility":4,"prerequisites":["Controlled lighting and camera mounting","Labelled defect image library 500+ per class","Line stop/reject mechanism integrated"],"valueRange":"30-60% reduction in downstream quality escapes; 15-25% less rework","keyRisk":"Novel defect types not in training set pass undetected until customer complaint","exemplar":"Automotive body panel line running 60 jobs/hour"},
    {"id":"make-vision-02","stage":"make","tech":"vision","robotics":False,"name":"Operator Safety Monitoring","oneLiner":"Video analytics detects PPE violations and zone breaches","how":"Real-time object detection tracks personnel, PPE compliance, and restricted zone entry. Alerts to supervisor dashboard; incident clips archived for review.","drivers":["risk"],"autonomy":3,"maturity":"scaling","impact":4,"feasibility":3,"prerequisites":["Camera coverage of hazard zones","Privacy and works council agreement","Incident response protocol defined"],"valueRange":"20-40% reduction in recordable incidents where deployed; insurance premium impact varies","keyRisk":"False alarms desensitise supervisors; privacy backlash if poorly communicated","exemplar":"Steel mill with molten metal handling zones"},
    {"id":"make-physics-01","stage":"make","tech":"physics","robotics":True,"name":"Adaptive Robotic Welding","oneLiner":"Robot adjusts weld path from 3-D seam profile sensing","how":"Structured light or laser profiling captures seam geometry; physics-informed path planner adjusts torch angle, speed, and weave in real time. Closed-loop quality verification.","drivers":["cost","quality"],"autonomy":4,"maturity":"scaling","impact":5,"feasibility":3,"prerequisites":["Robot with force/torque and vision guidance","Welding procedure qualification for adaptive mode","Skilled robot programmer for edge cases"],"valueRange":"20-40% reduction in weld rework; 10-15% cycle time improvement on variable joints","keyRisk":"Unqualified adaptive parameters on new joint geometries","exemplar":"Heavy fabrication shop with mixed batch welding"},
    {"id":"make-physics-02","stage":"make","tech":"physics","robotics":True,"name":"Cobotic Assembly Assist","oneLiner":"Collaborative robots assist with precise insertion tasks","how":"Force-controlled cobots guide operators through insertion paths with haptic feedback. 3-D vision confirms alignment before release. Learns operator pace over shifts.","drivers":["cost"],"autonomy":3,"maturity":"proving","impact":3,"feasibility":3,"prerequisites":["Ergonomic assessment of task suitability","Cobot safety assessment per ISO 10218","Operator acceptance and training programme"],"valueRange":"15-25% cycle time reduction on assisted tasks; reduced ergonomic injuries","keyRisk":"Operator over-reliance reduces skill retention for manual fallback","exemplar":"Electronics final assembly with connector insertion"},
    {"id":"make-physics-03","stage":"make","tech":"physics","robotics":True,"name":"AM Process Digital Twin","oneLiner":"Layer-by-layer simulation predicts distortion and porosity","how":"Thermo-mechanical simulation of additive build process predicts residual stress and distortion. In-situ monitoring (melt pool imaging) validates simulation in real time.","drivers":["cost","quality"],"autonomy":3,"maturity":"proving","impact":4,"feasibility":2,"prerequisites":["AM machine with in-situ monitoring","Material property database for simulation","Post-build CT validation capability"],"valueRange":"30-50% reduction in AM trial builds; faster qualification of new geometries","keyRisk":"Simulation-material mismatch on new powder lots","exemplar":"Aerospace AM service bureau printing titanium structural parts"},
    # QUALITY
    {"id":"quality-predictive-01","stage":"quality","tech":"predictive","robotics":False,"name":"Statistical Process Control Augmentation","oneLiner":"ML-enhanced control charts detect subtle drift patterns","how":"Beyond Western Electric rules, autoencoders and change-point detection identify multivariate drift patterns invisible to univariate SPC. Root-cause suggestions from correlated parameters.","drivers":["cost","quality"],"autonomy":2,"maturity":"proven","impact":4,"feasibility":4,"prerequisites":["High-frequency process data in historian","Defined reaction protocols per alert type","Quality engineer to validate ML findings"],"valueRange":"10-20% reduction in scrap on monitored processes","keyRisk":"Over-alerting on normal process noise degrades SPC programme credibility","exemplar":"Semiconductor packaging line with 200+ SPC charts"},
    {"id":"quality-predictive-02","stage":"quality","tech":"predictive","robotics":False,"name":"Batch Release Prediction","oneLiner":"Predicts lot acceptance from in-process data before testing completes","how":"Models trained on historical batch records predict final quality test outcomes from in-process measurements at intermediate stages. Enables early rework or hold decisions.","drivers":["cost","risk"],"autonomy":2,"maturity":"scaling","impact":4,"feasibility":3,"prerequisites":["Batch record digitisation","Validated model per product family","Regulatory acceptance of predictive release (industry-dependent)"],"valueRange":"1-3 day reduction in batch release cycle in pharma; reduced quarantine inventory","keyRisk":"Regulatory rejection if validation package is insufficient","exemplar":"Pharma oral solid dose facility under GMP"},
    {"id":"quality-generative-01","stage":"quality","tech":"generative","robotics":False,"name":"CAPA & Deviation Report Assistant","oneLiner":"Drafts investigation reports from event data and similar cases","how":"RAG retrieves similar historical deviations and CAPA outcomes. LLM drafts investigation narrative, root-cause analysis structure, and corrective action recommendations for human review.","drivers":["cost","risk"],"autonomy":1,"maturity":"scaling","impact":3,"feasibility":4,"prerequisites":["Quality event database with closed-loop history","Template aligned to regulatory expectations","QA approval mandatory before submission"],"valueRange":"30-50% reduction in investigation documentation time","keyRisk":"Suggested root cause that sounds plausible but is wrong, delaying true resolution","exemplar":"Biologics manufacturer with 200+ deviations per year"},
    {"id":"quality-vision-01","stage":"quality","tech":"vision","robotics":False,"name":"Automated Dimensional Inspection","oneLiner":"2-D/2.5-D vision measures critical dimensions in-line","how":"Calibrated vision systems extract edges and features, computing dimensions against CAD nominal with GD&T evaluation. SPC feedback to machining centres.","drivers":["cost","quality"],"autonomy":3,"maturity":"proven","impact":4,"feasibility":4,"prerequisites":["Part presentation repeatability","Camera calibration programme","GD&T rules engine configured per part family"],"valueRange":"60-80% reduction in CMM queue time; faster feedback loops","keyRisk":"Measurement uncertainty not properly budgeted against tolerance bands","exemplar":"Precision machining shop supplying medical implants"},
    {"id":"quality-vision-02","stage":"quality","tech":"vision","robotics":False,"name":"X-Ray & CT Defect Classification","oneLiner":"Deep learning on radiographic images finds internal defects","how":"CNNs trained on annotated X-ray and CT slices classify porosity, inclusions, and crack indications. Reduces human reviewer fatigue on high-volume inspection.","drivers":["quality","risk"],"autonomy":2,"maturity":"scaling","impact":5,"feasibility":3,"prerequisites":["Annotated image library with expert labels","NDT equipment with digital output","Human reviewer for borderline and critical parts"],"valueRange":"2-3x throughput on NDT review stations; fewer missed critical defects","keyRisk":"Adversarial defect morphologies not represented in training data","exemplar":"Aerospace casting supplier with 100% X-ray requirement"},
    {"id":"quality-vision-03","stage":"quality","tech":"vision","robotics":False,"name":"Label & Packaging Verification","oneLiner":"Vision confirms correct label, barcode, and leaflet on every unit","how":"Multi-camera setup verifies product-label match, barcode readability, and leaflet presence. OCR confirms lot/expiry against production order. Zero-defect shipping gate.","drivers":["risk","cost"],"autonomy":4,"maturity":"proven","impact":4,"feasibility":4,"prerequisites":["Golden sample images per SKU","Line integration for reject and divert","Serialisation compliance where required"],"valueRange":"Near-elimination of mislabel recalls; one avoided recall often saves $5M+","keyRisk":"Look-alike SKU confusion if product changeover validation is skipped","exemplar":"Pharma packaging line with 50+ SKU changeovers per week"},
    {"id":"quality-physics-01","stage":"quality","tech":"physics","robotics":False,"name":"Virtual Metrology","oneLiner":"Predicts final dimensions from process sensor data","how":"Physics-informed models map tool wear, temperature, and cutting forces to predicted part dimensions without physical measurement. Enables proactive tool change.","drivers":["cost","quality"],"autonomy":3,"maturity":"proving","impact":4,"feasibility":2,"prerequisites":["Instrumented machine tools with sensor feeds","Ground-truth CMM data for model training","Tool life management integration"],"valueRange":"20-40% reduction in CMM sampling; extended tool life on stable processes","keyRisk":"Model drift after tool geometry change or material lot shift","exemplar":"Automotive powertrain machining line"},
    # MAINTAIN
    {"id":"maintain-predictive-01","stage":"maintain","tech":"predictive","robotics":False,"name":"Fleet Health Dashboard","oneLiner":"Unified view of asset health across installed base","how":"Aggregates telemetry from field-deployed equipment to predict component failures and recommend service intervals. Prioritises field engineer dispatch by customer impact.","drivers":["revenue","cost"],"autonomy":2,"maturity":"scaling","impact":4,"feasibility":3,"prerequisites":["Connected product telemetry pipeline","Service parts inventory visibility","Field service management integration"],"valueRange":"10-20% reduction in warranty costs; 5-10% service revenue from proactive offers","keyRisk":"Customer pushback on data collection and privacy concerns","exemplar":"Industrial compressor OEM with 10,000 connected units"},
    {"id":"maintain-predictive-02","stage":"maintain","tech":"predictive","robotics":False,"name":"Spares Demand Forecasting","oneLiner":"Predicts spare parts demand from failure models and fleet age","how":"Combines reliability models with installed base age profiles to forecast spare parts demand by region. Optimises service stock levels and obsolescence planning.","drivers":["cost","capital"],"autonomy":2,"maturity":"proven","impact":3,"feasibility":4,"prerequisites":["Installed base registry with configuration data","Failure history linked to part numbers","Service logistics network model"],"valueRange":"15-25% reduction in service inventory; improved fill rates","keyRisk":"Demand spike from recall or design flaw not captured in failure models","exemplar":"Construction equipment OEM with global parts depots"},
    {"id":"maintain-generative-01","stage":"maintain","tech":"generative","robotics":False,"name":"Field Service Knowledge Assistant","oneLiner":"Mobile copilot for technicians with repair procedures and history","how":"RAG over service manuals, bulletins, and past work orders answers technician queries in the field. Suggests diagnostic steps based on symptom description.","drivers":["cost","revenue"],"autonomy":2,"maturity":"scaling","impact":4,"feasibility":4,"prerequisites":["Digitised service documentation","Mobile connectivity or offline cache","Feedback loop for answer quality"],"valueRange":"15-25% improvement in first-time fix rate; 20% reduction in senior tech escalations","keyRisk":"Incorrect diagnostic path on novel failure mode extends downtime","exemplar":"Medical imaging equipment service organisation"},
    {"id":"maintain-vision-01","stage":"maintain","tech":"vision","robotics":False,"name":"Remote Visual Inspection Assist","oneLiner":"Technician streams video; AI highlights anomalies and wear patterns","how":"Technician uses mobile camera or AR glasses to stream equipment condition. Vision models highlight corrosion, wear, and leak indicators against reference baselines.","drivers":["cost"],"autonomy":2,"maturity":"proving","impact":3,"feasibility":3,"prerequisites":["Reliable field connectivity or async upload","Reference image library per asset type","Expert review queue for flagged items"],"valueRange":"30-50% reduction in specialist dispatch for routine inspections","keyRisk":"Poor lighting or camera angle produces false assessments","exemplar":"Oil & gas upstream facility inspection programme"},
    {"id":"maintain-physics-01","stage":"maintain","tech":"physics","robotics":True,"name":"Autonomous Inspection Robot","oneLiner":"Mobile robot navigates facility capturing 3-D condition data","how":"AMR equipped with LiDAR, thermal, and visual sensors autonomously navigates predefined routes. Builds 3-D condition model compared against baseline for change detection.","drivers":["cost","risk"],"autonomy":4,"maturity":"proving","impact":4,"feasibility":2,"prerequisites":["Facility mapping and safety certification","Baseline 3-D scan of inspected assets","Maintenance programme willing to act on robot findings"],"valueRange":"40-60% reduction in manual inspection hours in hazardous areas","keyRisk":"Robot navigation failure in changed environments; missed defects in occluded areas","exemplar":"Chemical plant with weekly corrosion monitoring rounds"},
    {"id":"maintain-physics-02","stage":"maintain","tech":"physics","robotics":True,"name":"Drone-Based Infrastructure Survey","oneLiner":"Autonomous drones capture thermal and visual of hard-to-reach assets","how":"Flight-planned drones capture high-resolution imagery and thermal maps of stacks, roofs, and elevated pipe runs. 3-D reconstruction enables change detection over time.","drivers":["risk","cost"],"autonomy":4,"maturity":"scaling","impact":4,"feasibility":3,"prerequisites":["Aviation authority permits and pilot certification (or waiver)","Flight path planning software","Integration with asset management system"],"valueRange":"50-70% cost reduction vs scaffolding/rope access inspection","keyRisk":"Regulatory restrictions limit deployment; weather dependency","exemplar":"Power utility inspecting transmission infrastructure"},
    # DELIVER
    {"id":"deliver-predictive-01","stage":"deliver","tech":"predictive","robotics":False,"name":"Logistics Delay Prediction","oneLiner":"Predicts in-transit delays and recommends rerouting","how":"Models ingest carrier performance, weather, port congestion, and customs data to predict ETA deviations. Recommends proactive customer communication and alternate routing.","drivers":["revenue","cost"],"autonomy":2,"maturity":"proven","impact":4,"feasibility":4,"prerequisites":["TMS with carrier tracking integration","Customer communication workflow","Historical delay data for model training"],"valueRange":"5-10% improvement in OTIF; reduced premium freight on expedites","keyRisk":"Over-communication of predicted delays erodes customer confidence","exemplar":"Industrial parts distributor with global outbound logistics"},
    {"id":"deliver-predictive-02","stage":"deliver","tech":"predictive","robotics":False,"name":"Warehouse Slotting Optimiser","oneLiner":"Dynamic slot assignment based on pick frequency and affinity","how":"Optimisation algorithms continuously re-slot based on order patterns, product affinity, and seasonal shifts. Predicts pick path time reduction.","drivers":["cost"],"autonomy":3,"maturity":"scaling","impact":3,"feasibility":4,"prerequisites":["WMS with flexible slotting capability","Pick path time baseline measurement","Labour plan for re-slotting execution"],"valueRange":"8-15% pick productivity improvement; reduced congestion","keyRisk":"Excessive re-slotting churn disrupts warehouse rhythm","exemplar":"E-commerce fulfilment centre with 50K SKUs"},
    {"id":"deliver-generative-01","stage":"deliver","tech":"generative","robotics":False,"name":"Customs & Shipping Document Generator","oneLiner":"Auto-generates customs declarations from order and product data","how":"LLM maps product master, HS codes, and destination rules to generate compliant shipping documents. Flags missing data and regulatory changes.","drivers":["cost","risk"],"autonomy":2,"maturity":"scaling","impact":3,"feasibility":4,"prerequisites":["Product master with HS codes and origin data","Regulatory rule updates feed","Customs broker review for first-use countries"],"valueRange":"50-70% faster document preparation; fewer customs holds","keyRisk":"Regulatory change not reflected in rules engine causes shipment detention","exemplar":"Specialty chemicals exporter shipping to 40 countries"},
    {"id":"deliver-vision-01","stage":"deliver","tech":"vision","robotics":False,"name":"Outbound Quality Gate","oneLiner":"Final vision check before shipment loading","how":"Camera at dock door verifies pallet configuration, label placement, and damage-free condition. Blocks loading on mismatch with shipping manifest.","drivers":["risk","cost"],"autonomy":4,"maturity":"proven","impact":3,"feasibility":4,"prerequisites":["Standardised pallet presentation","Manifest integration with WMS","Loading dock camera infrastructure"],"valueRange":"Near-elimination of shipping wrong product; reduced customer claims","keyRisk":"Damage occurring after gate check but before customer receipt","exemplar":"Consumer goods DC shipping to retail distribution centres"},
    {"id":"deliver-physics-01","stage":"deliver","tech":"physics","robotics":True,"name":"Autonomous Mobile Robot Fleet","oneLiner":"AMRs transport materials within warehouse and plant","how":"Fleet management system coordinates AMRs for point-to-point and zone-to-zone material transport. 3-D facility map with dynamic obstacle avoidance and traffic management.","drivers":["cost"],"autonomy":4,"maturity":"scaling","impact":4,"feasibility":3,"prerequisites":["Facility layout assessment for AMR suitability","WMS/MES integration for transport triggers","Safety assessment and floor marking programme"],"valueRange":"20-35% material handling labour reduction in suitable environments","keyRisk":"Integration complexity with legacy systems delays ROI realisation","exemplar":"Automotive parts warehouse feeding JIT production lines"},
    # SERVE
    {"id":"serve-predictive-01","stage":"serve","tech":"predictive","robotics":False,"name":"Customer Churn & Upsell Prediction","oneLiner":"Identifies at-risk accounts and expansion opportunities","how":"Models combine product usage telemetry, service interaction history, and commercial data to score churn risk and cross-sell propensity. Triggers proactive outreach.","drivers":["revenue"],"autonomy":2,"maturity":"proven","impact":4,"feasibility":4,"prerequisites":["CRM with complete interaction history","Product usage data where applicable","Sales playbook for each score segment"],"valueRange":"5-15% reduction in churn on covered accounts; 3-8% upsell conversion lift","keyRisk":"Mis-timed outreach on false-positive churn signals annoys loyal customers","exemplar":"Industrial automation vendor with recurring service contracts"},
    {"id":"serve-generative-01","stage":"serve","tech":"generative","robotics":False,"name":"Customer Support Copilot","oneLiner":"Assists agents with product knowledge and case resolution","how":"RAG over product manuals, known issues, and resolved cases suggests responses and troubleshooting steps. Drafts customer communications in brand tone.","drivers":["cost","revenue"],"autonomy":2,"maturity":"scaling","impact":4,"feasibility":4,"prerequisites":["Knowledge base curation and freshness process","CRM integration for case context","Agent review before customer-facing send"],"valueRange":"20-30% reduction in average handle time; improved CSAT on complex cases","keyRisk":"Incorrect technical advice on safety-critical products creates liability","exemplar":"HVAC equipment manufacturer with 500+ active SKUs"},
    {"id":"serve-generative-02","stage":"serve","tech":"generative","robotics":False,"name":"Product Configuration Assistant","oneLiner":"Guides customers through complex product configuration","how":"Conversational agent navigates configuration rules, compatibility constraints, and pricing to assemble valid product configurations. Generates quotes and BOMs.","drivers":["revenue","cost"],"autonomy":3,"maturity":"proving","impact":4,"feasibility":3,"prerequisites":["Rules-based configurator backend","Pricing and availability integration","Fallback to human for non-standard requests"],"valueRange":"10-20% increase in self-service conversion; reduced config errors","keyRisk":"Invalid configurations that pass conversational check but fail engineering validation","exemplar":"Modular industrial pump manufacturer with 10^6 configuration combinations"},
    {"id":"serve-generative-03","stage":"serve","tech":"generative","robotics":False,"name":"Technical Training Content Generator","oneLiner":"Creates personalised training modules from product documentation","how":"LLM transforms product manuals and service procedures into role-specific training modules, quizzes, and simulations. Adapts difficulty to learner progress.","drivers":["cost"],"autonomy":2,"maturity":"emerging","impact":3,"feasibility":3,"prerequisites":["Structured product documentation corpus","LMS integration","Subject matter expert review of generated content"],"valueRange":"30-50% reduction in training content development time","keyRisk":"Training gaps on safety-critical procedures if source docs are incomplete","exemplar":"Material handling equipment company onboarding dealer technicians"},
    {"id":"serve-vision-01","stage":"serve","tech":"vision","robotics":False,"name":"Visual Product Identification Support","oneLiner":"Customer photos matched to product catalogue for support","how":"Customer uploads photo of installed product; vision model identifies model, variant, and common failure modes. Routes to correct support team with context.","drivers":["cost","revenue"],"autonomy":2,"maturity":"proving","impact":3,"feasibility":3,"prerequisites":["Product image library with variant coverage","Support routing rules by product ID","Customer-facing upload interface"],"valueRange":"15-25% reduction in misrouted support tickets","keyRisk":"Misidentification of similar-looking variants leads to wrong parts shipped","exemplar":"Plumbing fixtures company with extensive product line"},
    {"id":"serve-physics-01","stage":"serve","tech":"physics","robotics":False,"name":"Remote Equipment Digital Twin","oneLiner":"Customer-facing twin shows live performance and predicted maintenance","how":"Cloud-hosted digital twin mirrors field equipment physics model with live telemetry overlay. Customers see performance benchmarks, predicted maintenance, and upgrade scenarios.","drivers":["revenue","cost"],"autonomy":2,"maturity":"proving","impact":4,"feasibility":2,"prerequisites":["Connected product with telemetry pipeline","Physics model validated against field performance","Customer portal and data-sharing agreements"],"valueRange":"5-10% service contract attach rate increase; premium tier differentiation","keyRisk":"Performance data exposure creates competitive intelligence concerns for customers","exemplar":"Industrial robotics OEM offering predictive service tier"},
]

# Fix driver typo
for uc in USE_CASES:
    uc["drivers"] = [d if d != "quality" else "risk" for d in uc["drivers"]]

STAGES = ["plan", "design", "source", "make", "quality", "maintain", "deliver", "serve"]
TECH = ["predictive", "generative", "vision", "physics"]
DRIVERS = ["revenue", "cost", "capital", "risk", "sustainability"]
MATURITY = ["emerging", "proving", "scaling", "proven"]

def validate():
    errors = []
    cell_counts = {}
    for s in STAGES:
        for t in TECH:
            cell_counts[f"{s}-{t}"] = 0
    for uc in USE_CASES:
        if uc["stage"] not in STAGES:
            errors.append(f"{uc['id']}: invalid stage {uc['stage']}")
        if uc["tech"] not in TECH:
            errors.append(f"{uc['id']}: invalid tech {uc['tech']}")
        if uc["autonomy"] not in range(1, 5):
            errors.append(f"{uc['id']}: invalid autonomy")
        if uc["maturity"] not in MATURITY:
            errors.append(f"{uc['id']}: invalid maturity")
        for d in uc["drivers"]:
            if d not in DRIVERS:
                errors.append(f"{uc['id']}: invalid driver {d}")
        if uc["tech"] != "physics" and uc["robotics"]:
            errors.append(f"{uc['id']}: robotics flag on non-physics tech")
        cell_counts[f"{uc['stage']}-{uc['tech']}"] += 1
    print(f"Total use cases: {len(USE_CASES)}")
    print("\nCell distribution:")
    empty = []
    for s in STAGES:
        row = []
        for t in TECH:
            key = f"{s}-{t}"
            c = cell_counts[key]
            row.append(str(c))
            if c == 0:
                empty.append(key)
        print(f"  {s:10s} | {' | '.join(row)}")
    print(f"\nEmpty cells ({len(empty)}): {', '.join(empty)}")
    if errors:
        print("\nERRORS:")
        for e in errors:
            print(f"  {e}")
        raise SystemExit(1)
    print("\nMECE audit PASSED")
    return cell_counts, empty

if __name__ == "__main__":
    validate()
